name: Jekyll site CI_

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  # Updated to the latest version
    - name: Set up Node.js
      uses: actions/setup-node@v3  # Ensure you're using the latest version
      with:
        node-version: '20'  # Specify Node.js version to match GitHub Actions deprecation notes

    - name: Install Dependencies
      run: npm install

    - name: Update baseurl in _config.yml
      uses: fjogeleit/yaml-update-action@master
      with:
        valueFile: '_config.yml'
        propertyPath: 'baseurl'
        value: '/blog/'
        commitChange: false
        updateFile: true

    - name: Build the site
      run: |
        jekyll build --future  # Run Jekyll build directly if installed in the environment

    - name: Build CSS with Tailwind
      run: |
        npx tailwindcss -i ./assets/css/tailwind.css -o ./assets/css/style.css --minify  # Add CSS build step

    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.5.0
      with:
        build_dir: _site/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
